// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm7zgZetsMgN5k5LnxOJQNksNFpX2KWh8',
    appId: '1:291110879650:web:ab0b1680bec6132a0eb2fb',
    messagingSenderId: '291110879650',
    projectId: 'projetflutterds',
    authDomain: 'projetflutterds.firebaseapp.com',
    storageBucket: 'projetflutterds.firebasestorage.app',
    measurementId: 'G-5KYW6HGGZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgEBEWR2dWfPYp8LKyNBVfKBQ_O4Bwan4',
    appId: '1:291110879650:android:847bebcc715620e80eb2fb',
    messagingSenderId: '291110879650',
    projectId: 'projetflutterds',
    storageBucket: 'projetflutterds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEIa0751v1sj4VWEroUoDDAT2LL6oTKcI',
    appId: '1:291110879650:ios:387f05b2e706860c0eb2fb',
    messagingSenderId: '291110879650',
    projectId: 'projetflutterds',
    storageBucket: 'projetflutterds.firebasestorage.app',
    iosBundleId: 'com.example.projetflutterDs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEIa0751v1sj4VWEroUoDDAT2LL6oTKcI',
    appId: '1:291110879650:ios:387f05b2e706860c0eb2fb',
    messagingSenderId: '291110879650',
    projectId: 'projetflutterds',
    storageBucket: 'projetflutterds.firebasestorage.app',
    iosBundleId: 'com.example.projetflutterDs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm7zgZetsMgN5k5LnxOJQNksNFpX2KWh8',
    appId: '1:291110879650:web:de6a2720e67b6f400eb2fb',
    messagingSenderId: '291110879650',
    projectId: 'projetflutterds',
    authDomain: 'projetflutterds.firebaseapp.com',
    storageBucket: 'projetflutterds.firebasestorage.app',
    measurementId: 'G-XNYNJ38PM1',
  );
}
